"""
articles/models.py
==================

Core editorial domain: Category, Tag, Article, Comment, Reaction and
ArticleView (analytics). Slugs are auto-generated by ``signals.py``.
"""

from django.conf import settings
from django.core.exceptions import ValidationError
from django.core.validators import FileExtensionValidator, MinLengthValidator
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.text import slugify

from .managers import (
    ArticleManager,
    CategoryManager,
    CommentManager,
)


# ---------------------------------------------------------------------------
# Validators
# ---------------------------------------------------------------------------
def validate_image_size(image):
    """Reject featured images larger than 3 MB."""
    max_kb = 3 * 1024
    if image.size > max_kb * 1024:
        raise ValidationError(f"Image file too large (max {max_kb // 1024} MB).")


image_extension_validator = FileExtensionValidator(
    allowed_extensions=["jpg", "jpeg", "png", "webp", "gif"]
)


# ---------------------------------------------------------------------------
# Category & Tag
# ---------------------------------------------------------------------------
class Category(models.Model):
    name = models.CharField(max_length=80, unique=True)
    slug = models.SlugField(max_length=100, unique=True, blank=True)
    description = models.TextField(blank=True, max_length=500)
    icon = models.CharField(
        max_length=10,
        blank=True,
        help_text="Optional emoji shown in navigation, e.g. 📰",
    )
    order = models.PositiveSmallIntegerField(
        default=0,
        help_text="Lower numbers appear first in the navigation.",
    )
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)

    objects = CategoryManager()

    class Meta:
        verbose_name = "category"
        verbose_name_plural = "categories"
        ordering = ("order", "name")
        indexes = [models.Index(fields=["is_active", "order"])]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("articles:category_detail", kwargs={"slug": self.slug})

    @property
    def published_count(self):
        return self.articles.filter(status="published").count()


class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=60, unique=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = "tag"
        verbose_name_plural = "tags"
        ordering = ("name",)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("articles:tag_detail", kwargs={"slug": self.slug})

    @property
    def published_count(self):
        return self.articles.filter(status="published").count()


# ---------------------------------------------------------------------------
# Article
# ---------------------------------------------------------------------------
class Article(models.Model):
    class Status(models.TextChoices):
        DRAFT = "draft", "Draft"
        PENDING = "pending", "Pending Review"
        PUBLISHED = "published", "Published"
        REJECTED = "rejected", "Rejected"

    title = models.CharField(
        max_length=200,
        validators=[MinLengthValidator(8)],
        help_text="Aim for 50–120 characters for the best SEO.",
    )
    slug = models.SlugField(max_length=220, unique=True, blank=True)
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.PROTECT,
        related_name="articles",
    )
    category = models.ForeignKey(
        Category,
        on_delete=models.PROTECT,
        related_name="articles",
    )
    tags = models.ManyToManyField(Tag, blank=True, related_name="articles")

    featured_image = models.ImageField(
        upload_to="articles/%Y/%m/",
        blank=True,
        null=True,
        validators=[validate_image_size, image_extension_validator],
        help_text="JPG/PNG/WEBP, up to 3 MB. 1200×630 recommended.",
    )
    image_caption = models.CharField(max_length=200, blank=True)
    excerpt = models.CharField(
        max_length=300,
        validators=[MinLengthValidator(20)],
        help_text="Short summary used in lists, cards and search results.",
    )
    content = models.TextField(
        help_text="The full article body (rich text).",
    )

    status = models.CharField(
        max_length=10,
        choices=Status.choices,
        default=Status.DRAFT,
        db_index=True,
    )
    is_featured = models.BooleanField(
        default=False,
        help_text="Featured stories appear in the homepage hero.",
    )
    is_breaking = models.BooleanField(default=False)

    views_count = models.PositiveIntegerField(default=0, editable=False)

    # Editorial workflow metadata
    rejection_reason = models.TextField(blank=True)
    reviewed_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="reviewed_articles",
    )
    submitted_at = models.DateTimeField(null=True, blank=True)
    published_at = models.DateTimeField(null=True, blank=True, db_index=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects = ArticleManager()

    class Meta:
        ordering = ("-published_at", "-created_at")
        verbose_name = "article"
        verbose_name_plural = "articles"
        indexes = [
            models.Index(fields=["status", "published_at"]),
            models.Index(fields=["-views_count"]),
            models.Index(fields=["is_featured", "status"]),
            models.Index(fields=["category", "status"]),
        ]
        permissions = [
            ("can_review_articles", "Can review, approve or reject articles"),
            ("can_feature_articles", "Can mark articles as featured"),
        ]

    def __str__(self):
        return self.title

    # ------------------------------------------------------------------
    # URLs & SEO
    # ------------------------------------------------------------------
    def get_absolute_url(self):
        return reverse("articles:detail", kwargs={"slug": self.slug})

    @property
    def meta_description(self):
        return self.excerpt

    # ------------------------------------------------------------------
    # Workflow helpers
    # ------------------------------------------------------------------
    def submit(self):
        """Student/author sends the article into the editorial queue."""
        self.status = self.Status.PENDING
        self.submitted_at = timezone.now()
        self.rejection_reason = ""
        self.save(update_fields=[
            "status", "submitted_at", "rejection_reason", "updated_at",
        ])

    def publish(self, reviewer=None):
        self.status = self.Status.PUBLISHED
        self.published_at = timezone.now()
        if reviewer is not None:
            self.reviewed_by = reviewer
        self.rejection_reason = ""
        self.save(update_fields=[
            "status", "published_at", "reviewed_by",
            "rejection_reason", "updated_at",
        ])

    def reject(self, reason, reviewer=None):
        self.status = self.Status.REJECTED
        self.rejection_reason = reason
        if reviewer is not None:
            self.reviewed_by = reviewer
        self.save(update_fields=[
            "status", "rejection_reason", "reviewed_by", "updated_at",
        ])

    @property
    def is_published(self):
        return (
            self.status == self.Status.PUBLISHED
            and self.published_at is not None
            and self.published_at <= timezone.now()
        )

    # ------------------------------------------------------------------
    # Presentation helpers
    # ------------------------------------------------------------------
    @property
    def reading_time(self):
        """Rough reading time at 200 words per minute."""
        words = len(self.content.split())
        return max(1, round(words / 200))

    def related_articles(self, limit=3):
        """Other published articles in the same category / sharing tags."""
        qs = (
            Article.objects.published()
            .exclude(pk=self.pk)
            .filter(
                models.Q(category=self.category)
                | models.Q(tags__in=self.tags.all())
            )
            .distinct()
        )
        return qs[:limit]

    def reaction_counts(self):
        counts = {
            value: 0 for value, _label in Reaction.ReactionType.choices
        }
        rows = (
            self.reactions.values("reaction_type")
            .annotate(n=models.Count("id"))
        )
        for row in rows:
            counts[row["reaction_type"]] = row["n"]
        counts["total"] = sum(
            v for k, v in counts.items() if k != "total"
        )
        return counts

    @property
    def comment_count(self):
        return self.comments.approved().count()


# ---------------------------------------------------------------------------
# Comments (threaded, one level of replies)
# ---------------------------------------------------------------------------
class Comment(models.Model):
    article = models.ForeignKey(
        Article, on_delete=models.CASCADE, related_name="comments"
    )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="comments",
    )
    body = models.TextField(
        max_length=1000,
        validators=[MinLengthValidator(2)],
    )
    parent = models.ForeignKey(
        "self",
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name="replies",
        help_text="Set when this comment is a reply to another comment.",
    )
    is_approved = models.BooleanField(
        default=True,
        help_text="Unverified users' comments are held for moderation.",
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects = CommentManager()

    class Meta:
        ordering = ("created_at",)
        verbose_name = "comment"
        verbose_name_plural = "comments"
        indexes = [
            models.Index(fields=["article", "is_approved", "created_at"]),
        ]

    def __str__(self):
        return f"Comment by {self.user.username} on {self.article.title}"

    @property
    def is_reply(self):
        return self.parent_id is not None

    def approve(self):
        self.is_approved = True
        self.save(update_fields=["is_approved", "updated_at"])


# ---------------------------------------------------------------------------
# Reactions (one per user per article; user may change the type)
# ---------------------------------------------------------------------------
class Reaction(models.Model):
    class ReactionType(models.TextChoices):
        LIKE = "like", "👍 Like"
        LOVE = "love", "❤️ Love"
        INSIGHTFUL = "insightful", "💡 Insightful"

    article = models.ForeignKey(
        Article, on_delete=models.CASCADE, related_name="reactions"
    )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="reactions",
    )
    reaction_type = models.CharField(
        max_length=12, choices=ReactionType.choices, default=ReactionType.LIKE
    )
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ("-created_at",)
        constraints = [
            models.UniqueConstraint(
                fields=["article", "user"],
                name="unique_reaction_per_user_per_article",
            ),
        ]
        verbose_name = "reaction"
        verbose_name_plural = "reactions"

    def __str__(self):
        return f"{self.user.username} {self.reaction_type} → {self.article_id}"


# ---------------------------------------------------------------------------
# Article view log — analytics
# ---------------------------------------------------------------------------
class ArticleView(models.Model):
    article = models.ForeignKey(
        Article, on_delete=models.CASCADE, related_name="article_views"
    )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="article_views",
    )
    ip = models.GenericIPAddressField(null=True, blank=True)
    user_agent = models.CharField(max_length=400, blank=True)
    referrer = models.URLField(max_length=500, blank=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ("-timestamp",)
        verbose_name = "article view"
        verbose_name_plural = "article views"
        indexes = [
            models.Index(fields=["article", "timestamp"]),
            models.Index(fields=["-timestamp"]),
        ]

    def __str__(self):
        return f"View of {self.article_id} at {self.timestamp:%Y-%m-%d %H:%M}"
