# Generated by Django 5.1.15 on 2026-09-10 15:23

import apps.accounts.managers
import django.contrib.auth.validators
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('reader', 'Reader'), ('student', 'Student Contributor'), ('faculty', 'Faculty Author'), ('editor', 'Editor'), ('admin', 'Admin')], db_index=True, default='reader', help_text='Determines what the user can do in the portal.', max_length=20)),
                ('student_id', models.CharField(blank=True, help_text='Official IUBAT student ID (students only).', max_length=12, validators=[django.core.validators.RegexValidator(message='Student ID must be 6–12 digits (e.g. 02120345).', regex='^\\d{6,12}$')])),
                ('department', models.CharField(blank=True, choices=[('', '—'), ('CSE', 'Computer Science and Engineering'), ('EEE', 'Electrical and Electronic Engineering'), ('CE', 'Civil Engineering'), ('ME', 'Mechanical Engineering'), ('BBA', 'Business Administration'), ('MBA', 'Master of Business Administration'), ('ECON', 'Economics'), ('ENG', 'English'), ('AGRI', 'Agriculture'), ('NFS', 'Nutrition and Food Science'), ('NUR', 'Nursing'), ('OTHER', 'Other')], max_length=10)),
                ('batch', models.PositiveSmallIntegerField(blank=True, help_text='Admission year, e.g. 2024.', null=True)),
                ('profile_picture', models.ImageField(blank=True, help_text='Square image recommended (max 2 MB).', null=True, upload_to='profile_pictures/%Y/%m/')),
                ('bio', models.TextField(blank=True, help_text='Short author biography shown on your profile.', max_length=500)),
                ('is_verified', models.BooleanField(default=False, help_text='Verified accounts show a badge and are trusted.')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ('-date_joined',),
                'indexes': [models.Index(fields=['role', 'is_active'], name='accounts_cu_role_0d7945_idx'), models.Index(fields=['department'], name='accounts_cu_departm_c7799a_idx')],
            },
            managers=[
                ('objects', apps.accounts.managers.CustomUserManager()),
            ],
        ),
    ]
